KNOWN_BINARIES = [
    "*.avi",          # video
    "*.bin",          # binary
    "*.bmp",          # image
    "*.docx",         # ms-word
    "*.eot",          # font
    "*.exe",          # binary
    "*.gif",          # image
    "*.gz",           # compressed
    "*.heic",         # image
    "*.heif",         # image
    "*.ico",          # image
    "*.jpeg",         # image
    "*.jpg",          # image
    "*.m1v",          # video
    "*.m2a",          # audio
    "*.mov",          # video
    "*.mp2",          # audio
    "*.mp3",          # audio
    "*.mp4",          # video
    "*.mpa",          # video
    "*.mpe",          # video
    "*.mpeg",         # video
    "*.mpg",          # video
    "*.opus",         # audio
    "*.otf",          # font
    "*.pdf",          # pdf
    "*.png",          # image
    "*.pptx",         # ms-powerpoint
    "*.qt",           # video
    "*.rar",          # compressed
    "*.tar",          # compressed
    "*.tif",          # image
    "*.tiff",         # image
    "*.ttf",          # font
    "*.wasm",         # wasm
    "*.wav",          # audio
    "*.webm",         # video
    "*.wma",          # video
    "*.wmv",          # video
    "*.woff",         # font
    "*.woff2",        # font
    "*.xlsx",         # ms-excel
    "*.zip",          # compressed
]
